# General settings
date: today
institute: ""

# Format
format: revealjs
theme: solarized
number-sections: true
number-depth: 3
lang: en-US

# Slides settings
slide-level: 2
incremental: false
slide-number: true
show-slide-number: all
center-title-slide: true
logo: ""
smaller: true
progress: true
auto-stretch: true

# Metadata
kaywords: []
pagetitle: "template"
date-meta: today

# Additional files
css: styles/style.css
resource-path: 
  - assets